media: media
content:
  - name: page
    label: Pages
    type: collection
    path: src/pages
    fields:
      - name: title
        type: string
      - name: section
        type: string
      - name: body
        type: rich-text
